const ORDER_PRINT_ERRORS = {
  PAGE_COUNT_INVALID: "ORDER_PRINT_PAGE_COUNT_INVALID",
  BLANK_PAGE_COUNT_INVALID: "ORDER_BLANK_PAGE_COUNT_INVALID",
  CONTENT_ON_EVEN_PHYSICAL_PAGE: "ORDER_CONTENT_ON_EVEN_PHYSICAL_PAGE",
  BLANK_PAGE_NOT_EMPTY: "ORDER_BLANK_PAGE_NOT_EMPTY",
  BLANK_PAGE_HAS_NUMBER: "ORDER_BLANK_PAGE_HAS_NUMBER",
  APPROVAL_PAGE_NOT_LAST: "ORDER_APPROVAL_PAGE_NOT_LAST",
  APPROVAL_PAGE_NOT_ON_REVERSE: "ORDER_APPROVAL_PAGE_NOT_ON_REVERSE",
  EXTRA_BLANK_BEFORE_APPROVAL: "ORDER_EXTRA_BLANK_BEFORE_APPROVAL",
  EXTRA_BLANK_AFTER_APPROVAL: "ORDER_EXTRA_BLANK_AFTER_APPROVAL",
  LOGICAL_NUMBERING_INVALID: "ORDER_LOGICAL_NUMBERING_INVALID",
  MIRROR_MARGINS_ENABLED: "ORDER_MIRROR_MARGINS_ENABLED",
};

module.exports = ORDER_PRINT_ERRORS;
