// Optional integration test. Requires a TEST MongoDB replica set and npm deps.
// Always uses a fresh random database, never the database named in the URI.
const test = require("node:test");
const assert = require("node:assert/strict");
const { randomUUID } = require("node:crypto");
const fs = require("node:fs");
const vm = require("node:vm");
const path = require("node:path");
const { createRequire } = require("node:module");
function load(file, mocks) {
  const filename = path.resolve(__dirname, "..", file), module = { exports: {} };
  const realRequire = createRequire(filename);
  vm.runInNewContext(fs.readFileSync(filename, "utf8"), {
    module, exports: module.exports, require: name => Object.hasOwn(mocks, name) ? mocks[name] : realRequire(name),
    process, console, Date,
  }, { filename });
  return module.exports;
}
test("real Mongo transactions: concurrent admission, rollback, changed payload and release", {
  skip: !process.env.MONGO_TEST_URI, timeout: 120000,
}, async () => {
  const mongoose = require("mongoose");
  const dbName = `armiadoc_admission_test_${randomUUID().replaceAll("-", "")}`;
  await mongoose.connect(process.env.MONGO_TEST_URI, { dbName });
  try {
    const GenerationJob = require("../src/models/generationJob");
    const Source = mongoose.model("AdmissionTestSource", new mongoose.Schema({}, { strict: false }));
    await Source.createCollection();
    const models = { GenerationJob, documentModels: { report: Source } };
    const index = load("src/services/generation/ensureActiveJobIndex.js", { "../../models": models });
    await index.ensureActiveJobIndex();
    const find = async (clientId, session) => GenerationJob.findOne({ clientId, status: { $in: ["queued", "processing"] } }).session(session || null);
    const createJob = load("src/services/generation/createGenerationJob.js", {
      "../../models": models, "./findActiveGenerationJobByClientId": find,
      "./inlineExecutionOwner": { createExecutionOwner: async () => ({ kind: "queue" }) },
    });
    let starts = 0;
    const persist = load("src/services/generation/persistAndGenerate.js", {
      mongoose, "../../models": models, "./ensureActiveJobIndex": index,
      "./findActiveGenerationJobByClientId": find, "./createGenerationJob": createJob,
      "./startGeneration": async () => { starts++; },
    });
    const payload = { caseId: "test", documentType: "report", mode: "docx_only", data: { text: "same" } };
    const request = body => persist({ model: Source, payload: body, clientId: "test-client" });
    const results = await Promise.all(Array.from({ length: 20 }, () => request(payload)));
    assert.equal(new Set(results.map(r => String(r.job._id))).size, 1);
    assert.equal(starts, 1);
    assert.equal(await GenerationJob.countDocuments(), 1);
    assert.equal(await Source.countDocuments(), 1, "loser transactions must roll back source documents");
    await assert.rejects(request({ ...payload, data: { text: "changed" } }), { code: "ACTIVE_GENERATION_DATA_CONFLICT" });
    await GenerationJob.updateOne({ _id: results[0].job._id }, { $set: { status: "ready" } });
    await request(payload);
    assert.equal(starts, 2, "ready releases the active slot");
    assert.equal(await GenerationJob.countDocuments({ status: "queued" }), 1);
    // A different browser session has its own slot.
    await persist({ model: Source, payload, clientId: "another-client" });
    assert.equal(starts, 3);
  } finally {
    // The database name is generated by this test, not supplied by the operator.
    await mongoose.connection.dropDatabase();
    await mongoose.disconnect();
  }
});
